name: Cypress

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  chrome:
    runs-on: ubuntu-latest
    env:
      VITE_API_HOST: https://jsonplaceholder.typicode.com/
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run dev server
        run: yarn dev
      - name: Run cypress tests
        uses: cypress-io/github-action@v2
        timeout-minutes: 10
